### ISSUE TITLE
Subdomain routing

### ISSUE THREAD

**Issue by lucasdcrk** [cnvs/studio#12]
Hi! 

How can I override the routes files from this package for subdomain routing?
Just upgraded from the legacy frontend of the previous version of canvas, I loooove the new design but I placed my blog on a subdomain and I do not know how to route this new frontend to a subdomain.

Thanks for the good work!

**Comment by lucasdcrk** [comment]
Okay I just found how to do it.
For further reference: the package will publish routes to your routes/web.php file when you install it, just edit it accordingly.

**Comment by austintoddj** [comment]
Glad you got it sorted out @lucasdcrk! Let me know if you run into any more problems 👍
