### ISSUE TITLE
Studio doesn't show twitter posts

### ISSUE THREAD

**Issue by NXAO** [cnvs/studio#14]
When I added a tweet in the editor, I saw everything and everything was fine, but when I went to the frontend I did not find a tweet.

![image](https://user-images.githubusercontent.com/4406080/81945199-72e80580-9606-11ea-9191-17627adc7809.png)

**Comment by austintoddj** [comment]
Good call @NXAO 
If you want to open a PR and add these two lines in the `resources/stubs/views/app` file:

```
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js"></script>
<script src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

I can get that merged in
