### ISSUE TITLE
Rebuild the project

### ISSUE THREAD

**Issue by prodigital-design** [cnvs/studio#20]
I decided to change the text in PostScreen.vue, how to rebuild the project? I entered the npm run dev command but nothing happened

**Comment by austintoddj** [comment]
When you say nothing happened, do you mean it compiled the files but nothing changed?

Could you check your `webpack.mix.js `file and see if the paths are correct for building those stylesheets?

**Comment by prodigital-design** [comment]
How to rebuild app.js in the public folder ?

**Comment by austintoddj** [comment]
Studio assets are separate from your original app assets. So, when you compile everything with `npm run dev` you'll have `app.css`/`app.js` as well as `studio.css`/`studio.js`.

So, the same command is re-compiling everything every time, unless you've got it defined differently in your Mix file. Does that make sense?

**Comment by prodigital-design** [comment]
Thanks
