### ISSUE TITLE
400 on canvas/api/posts in production only

### ISSUE THREAD

**Issue by tj-mc** [cnvs/studio#24]
Hey there, been trying to debug a strange issue I'm facing with canvas/studio. In my production env (ubuntu 18), the server always returns an empty object on canvas/api/posts. However, on the local machine, this is not the case. I have tried everything I can think of, from reinstalling canvas and studio, restarting the machine and running migrations, but nothing seems to work.

**Comment by austintoddj** [comment]
Hm interesting. You can verify that there's post data available in your database on production? Also, do the /tags /topics routes give similar errors?

**Comment by tj-mc** [comment]
Hey, thanks for getting back so soon. I was able to inspect the data in the database and it appears to be the same as in the test environment. /tags and /topics give the correct response.

**Comment by austintoddj** [comment]
Good to know, thanks. Do you have a query string attached to your request like this?

```
example.com/canvas/api/posts?type=published
example.com/canvas/api/posts?type=draft
```

If not, try appending one of those and see if you get a different result. The next version of Canvas that's nearing completion isn't going to return an empty response by default. But for now, we have to just append the query type on each request and we'll get our data back.

**Comment by tj-mc** [comment]
Thanks, I checked and the full request url is `/canvas/api/posts?page=1&type=published`

**Comment by tj-mc** [comment]
Managed to resolve this by starting with a clean server and building up the project from the repo. If I manage to find out the source of it, I'll post here. Thanks for your help, this is a great project and has really saved me building an entire blog.

**Comment by austintoddj** [comment]
You're welcome @tj-mc, and thanks for the follow up! Let me know if there's anything else I can do to help.
